### ISSUE TITLE
Problem when creating a new workspace

### ISSUE THREAD

**Issue by voxrey** [JeremTech/Forge-Modding-Helper#1]
Hello,
When I create a new workspace, after entering all the information correctly, the folder with the name of my modid is generated, but it is empty and the application closes.
When I restart it, the project is on the list of recent workspaces but when I try to open it this image appears :
![image](https://user-images.githubusercontent.com/72698969/111677955-0a6a4600-8820-11eb-9482-f21908b38914.png)

Then an fmh folder is generated in my mod folder.

**Comment by JeremTech** [comment]
Hello !

It surely come from the Forge downloading step of the assistant creator.
Can you give the wanted Forge version and your Windows 10 version ?

EDIT : This can be also come from missing access rights on the output folder. Are you administrator on your session ?

Thanks for the report !

**Comment by voxrey** [comment]
Hey,

I use windows 10 (I'm admin and I try also with execute as administrator) and the forge version 36.1.0 for minecraft 1.16.5
![version](https://user-images.githubusercontent.com/72698969/111820622-03a40780-88e2-11eb-999e-6c02010eebbd.jpg)

**Comment by JeremTech** [comment]
I've tested and I have no problem with this Forge version.
One of my friend have also tested and he has no problems.

So I think this can be your antivirus software. If you have one, can you try to disable it, re-create your workspace, and see if this is working ?

**Comment by JeremTech** [comment]
@voXrey Any news ?
